# Generated by Django 6.0.8 on 2026-08-28 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(help_text='Utilisateur ayant envoyé le message.', on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='student',
            field=models.ForeignKey(help_text="Utilisateur à l'origine de la demande.", on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='support_request',
            field=models.ForeignKey(help_text='Demande de support à laquelle appartient le message.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportrequest', verbose_name='Demande de support'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['student', '-created_at'], name='supp_stud_date_id'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['status', '-created_at'], name='supp_req_stat_date_id'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['priority', 'status'], name='supp_req_prio_stat_id'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['support_request', 'created_at'], name='support_msg_request_date_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['sender', '-created_at'], name='support_msg_sender_date_idx'),
        ),
    ]
