# Generated by Django 6.0.8 on 2026-09-07 01:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(help_text='Contenu du message.', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message de ticket',
                'verbose_name_plural': 'Messages de ticket',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='supportmessage',
            name='support_msg_request_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportmessage',
            name='support_msg_sender_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='supportrequest',
            name='supp_stud_date_id',
        ),
        migrations.RemoveIndex(
            model_name='supportrequest',
            name='supp_req_stat_date_id',
        ),
        migrations.RemoveIndex(
            model_name='supportrequest',
            name='supp_req_prio_stat_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(help_text="Utilisateur à l'origine du ticket.", on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender',
            field=models.ForeignKey(help_text='Utilisateur ayant envoyé le message.', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(help_text='Ticket auquel appartient le message.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.ticket', verbose_name='Ticket'),
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='support_request',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='student',
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['student', '-created_at'], name='ticket_stud_date_id'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='ticket_stat_date_id'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', 'status'], name='ticket_prio_stat_id'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='ticket_msg_ticket_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['sender', '-created_at'], name='ticket_msg_sender_date_idx'),
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
        migrations.DeleteModel(
            name='SupportRequest',
        ),
    ]
