# Generated by Django 6.0.8 on 2026-09-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='establishment',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='contestsession',
            constraint=models.CheckConstraint(condition=models.Q(('registration_end_date__isnull', True), ('registration_start_date__isnull', True), ('registration_end_date__gte', models.F('registration_start_date')), _connector='OR'), name='session_registration_dates_ordering'),
        ),
        migrations.AddConstraint(
            model_name='contestsession',
            constraint=models.CheckConstraint(condition=models.Q(('exam_date__isnull', True), ('registration_end_date__isnull', True), ('exam_date__gte', models.F('registration_end_date')), _connector='OR'), name='session_exam_after_registration'),
        ),
    ]