# Generated by Django 6.0.8 on 2026-09-09 20:07

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_unit_price_cartitem_unit_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='prix unitaire figé'),
        ),
    ]
