# Generated by Django 6.0.8 on 2026-09-12 04:07

import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='line_discount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'XAF'), help_text='Remise totale pour cette ligne : remise unitaire x quantité.', max_digits=12, verbose_name='Remise de la ligne'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_subtotal',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'XAF'), help_text='Sous-total pour cette ligne avant remise : prix unitaire x quantité.', max_digits=12, verbose_name='Sous-total de la ligne'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=djmoney.models.fields.MoneyField(decimal_places=2, help_text='Total pour cette ligne après remise : sous-total de la ligne - remise de la ligne.', max_digits=12, verbose_name='Total de la ligne'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_discount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'XAF'), help_text="Remise par unité. Pour un produit : la remise active du produit au moment de la commande. Pour un pack : la somme des remises par unité de chaque produit à l'intérieur du pack.", max_digits=12, verbose_name='Remise unitaire'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, help_text='Prix original par unité (avant remise), calculé depuis le catalogue au moment de la commande.', max_digits=12, verbose_name='Prix unitaire'),
        ),
    ]
