# Generated by Django 6.0.8 on 2026-08-31 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('password_reset', 'Password reset')], max_length=30)),
                ('code_hash', models.CharField(max_length=255)),
                ('expiration_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='emailverification',
            options={'verbose_name': "Vérification d'adresse email", 'verbose_name_plural': "Vérifications d'adresses email"},
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de tentatives'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='code_hash',
            field=models.CharField(max_length=128, verbose_name='Hash du code de vérification'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='expires_at',
            field=models.DateTimeField(verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['expires_at'], name='email_verif_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['verified_at'], name='email_verif_verified_idx'),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='users_otp_user_id_eb7a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expiration_at'], name='users_otp_expirat_391801_idx'),
        ),
    ]
