# Generated by Django 6.0.8 on 2026-09-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_alter_emailverification_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverification',
            name='email_verif_expires_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailverification',
            name='email_verif_verified_idx',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
