# Generated by Django 6.0.8 on 2026-08-28 14:42

import django.db.models.deletion
import gradia.document.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contest', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('subject_file', models.FileField(upload_to=gradia.document.models.document_subject_upload_path)),
                ('correction_file', models.FileField(upload_to=gradia.document.models.document_correction_upload_path)),
                ('price', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('contest_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contest.contestsession')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('view_correction', 'Consultation de la correction'), ('download_subject', 'Téléchargement du sujet')], max_length=50)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='document.document')),
            ],
            options={
                'verbose_name': "Journal d'accès au document",
                'verbose_name_plural': "Journaux d'accès aux documents",
                'ordering': ['-accessed_at'],
            },
        ),
    ]
