# Generated by Django 6.0.8 on 2026-08-28 15:13

import django.db.models.deletion
import gradia.document.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='subject',
        ),
        migrations.AddField(
            model_name='document',
            name='context',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='document',
            name='correction_file',
            field=models.FileField(upload_to=gradia.document.models.document_correction_upload_path, verbose_name='Correction File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject_file',
            field=models.FileField(upload_to=gradia.document.models.document_subject_upload_path, verbose_name='Subject File'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='action',
            field=models.CharField(choices=[('view_correction', 'Consultation de la correction'), ('download_subject', 'Téléchargement du sujet')], max_length=50, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='document.document', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
