# Generated by Django 6.0.8 on 2026-09-03 13:43

import gradia.document.models
import gradia.document.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_document_subject_document_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Seuls les documents publiés sont visibles dans le catalogue et consultables par les étudiants.', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='document',
            name='correction_file',
            field=models.FileField(help_text='PDF, DOC or DOCX file.', storage=gradia.document.storages.ProtectedDocumentStorage(), upload_to=gradia.document.models.document_correction_upload_path, verbose_name='Correction File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject_file',
            field=models.FileField(help_text='PDF, DOC or DOCX file.', storage=gradia.document.storages.ProtectedDocumentStorage(), upload_to=gradia.document.models.document_subject_upload_path, verbose_name='Subject File'),
        ),
    ]
