# Generated by Django 6.0.8 on 2026-09-07 01:38

import gradia.document.models
import gradia.document.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_document_is_published_alter_document_correction_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='correction_file',
            field=models.FileField(help_text='PDF or DOCX file.', storage=gradia.document.storages.ProtectedDocumentStorage(), upload_to=gradia.document.models.document_correction_upload_path, verbose_name='Correction File'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subject_file',
            field=models.FileField(help_text='PDF or DOCX file.', storage=gradia.document.storages.ProtectedDocumentStorage(), upload_to=gradia.document.models.document_subject_upload_path, verbose_name='Subject File'),
        ),
    ]
