# Generated by Django 6.0.8 on 2026-09-24 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='réponse du fournisseur'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Identifiant de transaction fourni par le prestataire.', max_length=200, verbose_name='ID de transaction fournisseur'),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe (Card)'), ('flutterwave_mobile_money', 'Flutterwave Mobile Money')], max_length=50, verbose_name='fournisseur')),
                ('event_id', models.CharField(max_length=255, verbose_name="identifiant de l'événement")),
                ('event_type', models.CharField(max_length=255, verbose_name="type d'événement")),
                ('payload', models.JSONField(default=dict, verbose_name='payload')),
                ('signature', models.TextField(blank=True, verbose_name='signature')),
                ('remote_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='date de réception')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('processing_status', models.CharField(choices=[('received', 'Reçu'), ('processing', 'En cours de traitement'), ('processed', 'Traité'), ('failed', 'Échec')], db_index=True, default='received', max_length=20, verbose_name='statut de traitement')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
            ],
            options={
                'verbose_name': 'événement webhook',
                'verbose_name_plural': 'événements webhook',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_payment_webhook_event')],
            },
        ),
    ]
